name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cc: [gcc, clang, tcc]
    steps:
    - uses: actions/checkout@v1
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential
        sudo apt-get install clang tcc libncurses-dev

    - name: Build with ${{ matrix.cc }}
      run: |
        autoreconf -i -f
        CC=${{ matrix.cc }} ./configure
        make
